name:                tetris
version:             0.1.0.0
license:             GPLv3

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- vector-sized

library:
  source-dirs: src

default-extensions:
- RecordWildCards
