name:                tetris
version:             0.1.0.0
license:             GPLv3

dependencies:
- base >= 4.7 && < 5
- vector-sized
- JuicyPixels
- finite-typelits
- process
- mtl
- time

library:
  source-dirs: src

executables:
  stream:
    source-dirs: .
    main: Main.hs
    ghc-options:
    - -O2
    dependencies:
    - tetris

default-extensions:
- DataKinds
- KindSignatures
- OverloadedLists
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- TypeApplications
- ViewPatterns
